//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunCat365.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RunCat365.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 40fps.
        /// </summary>
        internal static string FPS_10 {
            get {
                return ResourceManager.GetString("FPS_10", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 20fps.
        /// </summary>
        internal static string FPS_20 {
            get {
                return ResourceManager.GetString("FPS_20", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 30fps.
        /// </summary>
        internal static string FPS_30 {
            get {
                return ResourceManager.GetString("FPS_30", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 40fps.
        /// </summary>
        internal static string FPS_40 {
            get {
                return ResourceManager.GetString("FPS_40", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Endless Game.
        /// </summary>
        internal static string Menu_EndlessGame {
            get {
                return ResourceManager.GetString("Menu_EndlessGame", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FPS Max Limit.
        /// </summary>
        internal static string Menu_FPSMaxLimit {
            get {
                return ResourceManager.GetString("Menu_FPSMaxLimit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Menu_Information {
            get {
                return ResourceManager.GetString("Menu_Information", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Launch at startup.
        /// </summary>
        internal static string Menu_LaunchAtStartup {
            get {
                return ResourceManager.GetString("Menu_LaunchAtStartup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open Repository.
        /// </summary>
        internal static string Menu_OpenRepository {
            get {
                return ResourceManager.GetString("Menu_OpenRepository", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Runners.
        /// </summary>
        internal static string Menu_Runners {
            get {
                return ResourceManager.GetString("Menu_Runners", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Menu_Theme {
            get {
                return ResourceManager.GetString("Menu_Theme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to App has launched. If the icon is not on the taskbar, it has been omitted, so please move it manually and pin it..
        /// </summary>
        internal static string Message_AppLaunched {
            get {
                return ResourceManager.GetString("Message_AppLaunched", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Message_Warning {
            get {
                return ResourceManager.GetString("Message_Warning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cat.
        /// </summary>
        internal static string Runner_Cat {
            get {
                return ResourceManager.GetString("Runner_Cat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Horse.
        /// </summary>
        internal static string Runner_Horse {
            get {
                return ResourceManager.GetString("Runner_Horse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parrot.
        /// </summary>
        internal static string Runner_Parrot {
            get {
                return ResourceManager.GetString("Runner_Parrot", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string Theme_System {
            get {
                return ResourceManager.GetString("Theme_System", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Endless Game.
        /// </summary>
        internal static string Window_EndlessGame {
            get {
                return ResourceManager.GetString("Window_EndlessGame", resourceCulture);
            }
        }
    }
}
